import Link from "next/link";
import { notFound } from "next/navigation";
import { z } from "zod";
import AdminForm from "@/components/admin/AdminForm";
import AdminShell from "@/components/admin/AdminShell";
import { bookShipment, saveOrderNote, updateOrder } from "@/app/admin/actions";
import { adminPageUser,money } from "@/lib/admin";
import { db } from "@/lib/db";

type Order={number:string;email:string;phone:string;shipping_address:Record<string,string>;status:string;payment_status:string;fulfillment_status:string;grand_total:number;subtotal:number;decoration_total:number;discount_total:number;shipping_total:number;tax_total:number;discount_code:string|null;notes:string|null;tracking_number:string|null;shipment_id:string|null;shipment_provider:string|null;courier_name:string|null;shipment_status:string|null;tracking_url:string|null;shipping_label_url:string|null;shipment_error:string|null;razorpay_order_id:string|null;razorpay_payment_id:string|null;created_at:Date;updated_at:Date};
type Item={id:string;product_name:string;sku:string;colour:string;size:string;method:string;quantity:number;unit_price:number;decoration_price:number;designs:unknown;artwork_status:string};
type Event={id:string;event:string;details:unknown;created_at:Date};

export default async function Page({params}:{params:Promise<{id:string}>}){
  await adminPageUser();const {id}=await params;if(!z.string().uuid().safeParse(id).success)notFound();
  const [orders,items,events]=await Promise.all([
    db()<Order[]>`SELECT * FROM orders WHERE id=${id}`,
    db()<Item[]>`SELECT id,product_name,sku,colour,size,method,quantity,unit_price,decoration_price,designs,artwork_status FROM order_items WHERE order_id=${id} ORDER BY created_at`,
    db()<Event[]>`SELECT id,event,details,created_at FROM order_events WHERE order_id=${id} ORDER BY created_at DESC`,
  ]);const order=orders[0];if(!order)notFound();const closed=["cancelled","refunded"].includes(order.status);
  return <AdminShell title={order.number} active="/admin/orders">
    <div className="mb-5 flex flex-wrap items-center justify-between gap-3"><Link href="/admin/orders" className="underline underline-offset-4">Back to orders</Link><span className="text-[12px] text-muted">Created {new Date(order.created_at).toLocaleString("en-IN")} · updated {new Date(order.updated_at).toLocaleString("en-IN")}</span></div>
    <div className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]">
      <section className="border border-line bg-white p-5"><h2 className="text-lg font-medium">Customer and delivery</h2><p className="mt-3 break-all">{order.email}</p><p>{order.phone}</p><address className="mt-3 not-italic text-[14px] leading-6">{["recipient","name","line1","line2","city","state","postalCode","postal_code"].filter((key,index,list)=>order.shipping_address[key]&&list.findIndex(item=>order.shipping_address[item]===order.shipping_address[key])===index).map(key=><p key={key}>{order.shipping_address[key]}</p>)}</address></section>
      <section className="border border-line bg-white p-5"><h2 className="text-lg font-medium">Amount and payment</h2><dl className="mt-4 grid grid-cols-[1fr_auto] gap-y-2 text-[13px]"><dt>Items</dt><dd>{money(order.subtotal)}</dd><dt>Decoration</dt><dd>{money(order.decoration_total)}</dd><dt>Discount {order.discount_code&&`(${order.discount_code})`}</dt><dd>-{money(order.discount_total)}</dd><dt>Shipping</dt><dd>{money(order.shipping_total)}</dd><dt>Tax</dt><dd>{money(order.tax_total)}</dd><dt className="border-t border-line pt-3 font-medium">Total</dt><dd className="border-t border-line pt-3 text-lg font-medium">{money(order.grand_total)}</dd></dl><div className="mt-4 border-t border-line pt-4 text-[12px] text-muted"><p>Payment: {order.payment_status}</p><p>Razorpay order: {order.razorpay_order_id??"—"}</p><p>Payment ID: {order.razorpay_payment_id??"—"}</p></div></section>
    </div>
    <section className="mt-5 border border-line bg-white p-5"><h2 className="text-lg font-medium">Operations</h2>{closed?<p className="mt-3 text-[13px] text-muted">This order is closed as {order.status}. Financial reconciliation is intentionally not available through a simple status edit.</p>:<AdminForm action={updateOrder} className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-[180px_190px_minmax(180px,1fr)_auto] lg:items-end"><input type="hidden" name="id" value={id}/><label className="text-[11px] text-muted">Order stage<select name="status" defaultValue={order.status} className="mt-1 h-10 w-full border border-line px-2">{["pending","confirmed","in_production","shipped","delivered"].map(value=><option key={value}>{value}</option>)}</select></label><label className="text-[11px] text-muted">Fulfilment<select name="fulfillment" defaultValue={order.fulfillment_status} className="mt-1 h-10 w-full border border-line px-2">{["unfulfilled","processing","fulfilled","returned"].map(value=><option key={value}>{value}</option>)}</select></label><label className="text-[11px] text-muted">Tracking / AWB<input name="tracking" defaultValue={order.tracking_number??""} className="mt-1 h-10 w-full border border-line px-3"/></label><button className="h-10 bg-ink px-5 text-white">Update order</button></AdminForm>}<div className="mt-4 flex flex-wrap gap-3 border-t border-line pt-4">{order.payment_status==="paid"&&!closed&&<AdminForm action={bookShipment}><input type="hidden" name="id" value={id}/><button className="h-10 bg-lime px-5">{order.shipment_id?"Complete / retry booking":"Book Shiprocket shipment"}</button></AdminForm>}{order.shipping_label_url&&<a href={order.shipping_label_url} target="_blank" rel="noreferrer" className="flex h-10 items-center border border-ink px-5 text-[12px]">Download shipping label</a>}{order.tracking_url&&<a href={order.tracking_url} target="_blank" rel="noreferrer" className="flex h-10 items-center border border-line px-5 text-[12px]">Open tracking</a>}</div>{order.shipment_id&&<p className="mt-3 text-[12px] text-muted">{order.shipment_provider??"Shipping provider"} · shipment {order.shipment_id} · {order.courier_name??"courier pending"} · {order.shipment_status??"status pending"}</p>}{order.shipment_error&&<p className="mt-3 border border-[#d9a6a6] bg-[#fff7f7] p-3 text-[12px] text-[#a32d2d]">{order.shipment_error}</p>}</section>
    <section className="mt-5"><h2 className="text-xl font-medium">Order items and production specifications</h2><div className="mt-3 space-y-3">{items.map(item=><article key={item.id} className="border border-line bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-medium">{item.product_name}</h3><p className="mt-1 text-[12px] text-muted">{item.sku} · {item.colour} / {item.size} · {item.method} · quantity {item.quantity}</p></div><div className="text-right"><p>{money((item.unit_price+item.decoration_price)*item.quantity)}</p><p className="text-[11px] text-muted">Artwork {item.artwork_status}</p></div></div><details className="mt-3"><summary className="cursor-pointer text-[13px]">View saved artwork specifications</summary><pre className="mt-3 max-h-80 overflow-auto whitespace-pre-wrap break-all bg-alt p-3 text-xs">{JSON.stringify(item.designs,null,2)}</pre></details></article>)}</div></section>
    <div className="mt-5 grid gap-5 xl:grid-cols-2"><AdminForm action={saveOrderNote} className="border border-line bg-white p-5"><input type="hidden" name="id" value={id}/><h2 className="text-lg font-medium">Internal order note</h2><textarea name="note" defaultValue={order.notes??""} rows={6} maxLength={2000} className="mt-3 w-full border border-line p-3"/><button className="mt-3 h-10 bg-ink px-5 text-white">Save note</button></AdminForm><section className="border border-line bg-white p-5"><h2 className="text-lg font-medium">Order timeline</h2><div className="mt-3 max-h-[360px] overflow-y-auto">{events.map(event=><details key={event.id} className="border-t border-line py-3 first:border-t-0"><summary className="cursor-pointer text-[13px]">{new Date(event.created_at).toLocaleString("en-IN")} · {event.event.replaceAll("_"," ")}</summary><pre className="mt-2 overflow-auto whitespace-pre-wrap break-all bg-alt p-2 text-[11px]">{JSON.stringify(event.details,null,2)}</pre></details>)}{!events.length&&<p className="text-muted">No events recorded yet.</p>}</div></section></div>
  </AdminShell>;
}
