import AdminForm from "@/components/admin/AdminForm";
import AdminShell from "@/components/admin/AdminShell";
import { createVariant, updateInventory } from "@/app/admin/actions";
import { adminPageUser } from "@/lib/admin";
import { db } from "@/lib/db";

type Row = { id:string; product_name:string; sku:string; colour:string; size:string; stock:number; low_stock_at:number };
export default async function Page() {
  await adminPageUser();
  const rows = await db()<Row[]>`SELECT v.id,p.name product_name,v.sku,v.colour,v.size,v.stock,v.low_stock_at FROM product_variants v JOIN products p ON p.id=v.product_id WHERE v.active=true ORDER BY (v.stock<=v.low_stock_at) DESC,p.name,v.colour,v.size`;const productRows=await db()<Array<{id:string;name:string;slug:string}>>`SELECT id,name,slug FROM products WHERE status<>'archived' ORDER BY name`;
  return <AdminShell title="Inventory" active="/admin/inventory"><details className="mb-5 border border-line bg-white p-5"><summary className="cursor-pointer font-medium">Add a colour / size variant</summary><AdminForm action={createVariant} className="mt-5 grid gap-4 sm:grid-cols-3 lg:grid-cols-6 lg:items-end"><label className="text-[11px] text-muted">Product<select name="productId" className="mt-1 h-10 w-full border border-line px-2 text-ink">{productRows.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><input type="hidden" name="slug" value={productRows[0]?.slug??''}/><label className="text-[11px] text-muted">Colour<input required name="colour" className="mt-1 h-10 w-full border border-line px-3"/></label><label className="text-[11px] text-muted">Hex<input required name="colourHex" defaultValue="#0a0a0a" className="mt-1 h-10 w-full border border-line px-3"/></label><label className="text-[11px] text-muted">Size<input required name="size" defaultValue="M" className="mt-1 h-10 w-full border border-line px-3"/></label><label className="text-[11px] text-muted">Stock<input required name="stock" type="number" min="0" defaultValue="0" className="mt-1 h-10 w-full border border-line px-3"/></label><button className="h-10 bg-lime px-4">Add variant</button></AdminForm></details><div className="overflow-x-auto border border-line bg-white"><table className="w-full min-w-[760px] text-left text-[13px]"><thead className="bg-alt text-[11px] uppercase tracking-[0.08em] text-muted"><tr><th className="p-4">Product</th><th>SKU</th><th>Variant</th><th>State</th><th className="p-4">Quantity</th></tr></thead><tbody className="divide-y divide-line">{rows.map((v)=><tr key={v.id}><td className="p-4 font-medium">{v.product_name}</td><td className="text-muted">{v.sku}</td><td>{v.colour} / {v.size}</td><td><span className={v.stock<=v.low_stock_at?"text-[#a32d2d]":"text-[#5f7f06]"}>{v.stock<=v.low_stock_at?"Low stock":"Available"}</span></td><td className="p-4"><AdminForm action={updateInventory} className="flex gap-2"><input type="hidden" name="id" value={v.id}/><input name="stock" type="number" min="0" defaultValue={v.stock} className="h-9 w-20 border border-line px-2"/><button className="h-9 border border-ink px-3">Update</button></AdminForm></td></tr>)}</tbody></table></div></AdminShell>;
}
