import Link from "next/link";
import AdminForm from "@/components/admin/AdminForm";
import AdminShell from "@/components/admin/AdminShell";
import { createVariant, updateInventory } from "@/app/admin/actions";
import { adminPageUser } from "@/lib/admin";
import { db } from "@/lib/db";

type Row={id:string;product_id:string;product_name:string;sku:string;colour:string;size:string;stock:number;reserved_stock:number;low_stock_at:number};
type Movement={id:string;sku:string;product_name:string;quantity:number;reason:string;reference:string|null;actor:string|null;created_at:Date};

export default async function Page({searchParams}:{searchParams:Promise<{q?:string;state?:string}>}){
  await adminPageUser();const search=await searchParams;const q=(search.q??"").trim().slice(0,100);const state=["all","low","reserved","out"].includes(search.state??"")?String(search.state):"all";const pattern=`%${q}%`;
  const [rows,productRows,movements]=await Promise.all([
    db()<Row[]>`SELECT v.id,v.product_id,p.name product_name,v.sku,v.colour,v.size,v.stock,v.reserved_stock,v.low_stock_at FROM product_variants v JOIN products p ON p.id=v.product_id WHERE v.active=true AND (${q}='' OR p.name ILIKE ${pattern} OR v.sku ILIKE ${pattern} OR v.colour ILIKE ${pattern}) AND (${state}='all' OR (${state}='low' AND v.stock-v.reserved_stock<=v.low_stock_at) OR (${state}='reserved' AND v.reserved_stock>0) OR (${state}='out' AND v.stock-v.reserved_stock<=0)) ORDER BY (v.stock-v.reserved_stock<=v.low_stock_at) DESC,p.name,v.colour,v.size LIMIT 500`,
    db()<Array<{id:string;name:string}>>`SELECT id,name FROM products WHERE status<>'archived' ORDER BY name`,
    db()<Movement[]>`SELECT m.id,v.sku,p.name product_name,m.quantity,m.reason,m.reference,u.email actor,m.created_at FROM inventory_movements m JOIN product_variants v ON v.id=m.variant_id JOIN products p ON p.id=v.product_id LEFT JOIN users u ON u.id=m.actor_id ORDER BY m.created_at DESC LIMIT 40`,
  ]);
  return <AdminShell title="Inventory" active="/admin/inventory">
    <form className="mb-5 grid gap-3 border border-line bg-white p-4 sm:grid-cols-[minmax(0,1fr)_180px_auto_auto]" method="get"><label className="text-[11px] text-muted">Search<input name="q" defaultValue={q} placeholder="Product, SKU or colour" className="mt-1 h-10 w-full border border-line px-3 text-ink"/></label><label className="text-[11px] text-muted">Stock state<select name="state" defaultValue={state} className="mt-1 h-10 w-full border border-line px-2 text-ink"><option value="all">All active</option><option value="low">Low stock</option><option value="reserved">Has reservations</option><option value="out">No sellable stock</option></select></label><button className="h-10 self-end bg-ink px-5 text-white">Filter</button><Link href="/admin/inventory" className="flex h-10 items-center self-end justify-center border border-line px-5">Reset</Link></form>
    <details className="mb-5 border border-line bg-white p-5"><summary className="cursor-pointer font-medium">Add a colour / size variant</summary><AdminForm action={createVariant} className="mt-5 grid gap-4 sm:grid-cols-3 lg:grid-cols-6 lg:items-end"><label className="text-[11px] text-muted">Product<select name="productId" className="mt-1 h-10 w-full border border-line px-2 text-ink">{productRows.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="text-[11px] text-muted">Colour<input required name="colour" className="mt-1 h-10 w-full border border-line px-3"/></label><label className="text-[11px] text-muted">Hex<input required name="colourHex" defaultValue="#0a0a0a" className="mt-1 h-10 w-full border border-line px-3"/></label><label className="text-[11px] text-muted">Size<input required name="size" defaultValue="M" className="mt-1 h-10 w-full border border-line px-3"/></label><label className="text-[11px] text-muted">Stock<input required name="stock" type="number" min="0" defaultValue="0" className="mt-1 h-10 w-full border border-line px-3"/></label><button className="h-10 bg-lime px-4">Add variant</button></AdminForm></details>
    <div className="overflow-x-auto border border-line bg-white"><table className="w-full min-w-[900px] text-left text-[13px]"><thead className="bg-alt text-[11px] uppercase tracking-[0.08em] text-muted"><tr><th className="p-4">Product</th><th>SKU</th><th>Variant</th><th>On hand</th><th>Reserved</th><th>Sellable</th><th>State</th><th className="p-4">Set on hand</th></tr></thead><tbody className="divide-y divide-line">{rows.map(v=>{const sellable=v.stock-v.reserved_stock;return <tr key={v.id}><td className="p-4 font-medium"><Link href={`/admin/products/${v.product_id}`} className="underline-offset-4 hover:underline">{v.product_name}</Link></td><td className="text-muted">{v.sku}</td><td>{v.colour} / {v.size}</td><td>{v.stock}</td><td>{v.reserved_stock}</td><td>{sellable}</td><td><span className={sellable<=v.low_stock_at?"text-[#a32d2d]":"text-[#5f7f06]"}>{sellable<=0?"Out of stock":sellable<=v.low_stock_at?"Low stock":"Available"}</span></td><td className="p-4"><AdminForm action={updateInventory} className="flex gap-2"><input type="hidden" name="id" value={v.id}/><input name="stock" type="number" min={v.reserved_stock} defaultValue={v.stock} className="h-9 w-20 border border-line px-2"/><button className="h-9 border border-ink px-3">Update</button></AdminForm></td></tr>})}</tbody></table>{!rows.length&&<p className="p-5 text-muted">No variants match these filters.</p>}</div>
    <section className="mt-6 border border-line bg-white"><div className="border-b border-line p-5"><h2 className="text-xl font-medium">Inventory movement log</h2><p className="mt-1 text-[13px] text-muted">Latest 40 stock changes across the catalogue.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-[13px]"><thead className="bg-alt text-[11px] uppercase tracking-[.08em] text-muted"><tr><th className="p-4">Time</th><th>Product / SKU</th><th>Change</th><th>Reason</th><th>Reference / actor</th></tr></thead><tbody className="divide-y divide-line">{movements.map(item=><tr key={item.id}><td className="p-4">{new Date(item.created_at).toLocaleString("en-IN")}</td><td>{item.product_name}<span className="block text-[11px] text-muted">{item.sku}</span></td><td className={item.quantity<0?"text-[#a32d2d]":"text-[#5f7f06]"}>{item.quantity>0?"+":""}{item.quantity}</td><td>{item.reason}</td><td>{item.reference??item.actor??"System"}</td></tr>)}</tbody></table>{!movements.length&&<p className="p-5 text-muted">No stock movements recorded yet.</p>}</div></section>
  </AdminShell>;
}
