import Link from "next/link";
import AdminForm from "@/components/admin/AdminForm";
import AdminShell from "@/components/admin/AdminShell";
import { bookShipment, updateOrder } from "@/app/admin/actions";
import { adminPageUser, money, shortDate } from "@/lib/admin";
import { db } from "@/lib/db";

type Row={id:string;number:string;email:string;phone:string;grand_total:number;status:string;payment_status:string;fulfillment_status:string;tracking_number:string|null;shipment_id:string|null;shipment_status:string|null;courier_name:string|null;shipping_label_url:string|null;shipment_error:string|null;created_at:Date;items:number};

export default async function Page({searchParams}:{searchParams:Promise<{q?:string;status?:string;payment?:string;page?:string}>}){
  await adminPageUser();const search=await searchParams;const q=(search.q??"").trim().slice(0,100);const status=["all","pending","confirmed","in_production","shipped","delivered","cancelled","refunded","shipment_error"].includes(search.status??"")?String(search.status):"all";const payment=["all","pending","paid","failed","refunded","partially_refunded"].includes(search.payment??"")?String(search.payment):"all";const page=Math.max(1,Number.parseInt(search.page??"1",10)||1);const limit=50;const offset=(page-1)*limit;const pattern=`%${q}%`;
  const whereQuery=db()<Row[]>`SELECT o.*,count(i.id)::int items FROM orders o LEFT JOIN order_items i ON i.order_id=o.id WHERE (${q}='' OR o.number ILIKE ${pattern} OR o.email ILIKE ${pattern} OR o.phone ILIKE ${pattern} OR coalesce(o.tracking_number,'') ILIKE ${pattern}) AND (${status}='all' OR (${status}='shipment_error' AND o.shipment_error IS NOT NULL) OR o.status=${status}) AND (${payment}='all' OR o.payment_status=${payment}) GROUP BY o.id ORDER BY o.created_at DESC LIMIT ${limit} OFFSET ${offset}`;
  const [rows,countRows]=await Promise.all([whereQuery,db()<Array<{count:number}>>`SELECT count(*)::int count FROM orders o WHERE (${q}='' OR o.number ILIKE ${pattern} OR o.email ILIKE ${pattern} OR o.phone ILIKE ${pattern} OR coalesce(o.tracking_number,'') ILIKE ${pattern}) AND (${status}='all' OR (${status}='shipment_error' AND o.shipment_error IS NOT NULL) OR o.status=${status}) AND (${payment}='all' OR o.payment_status=${payment})`]);const total=countRows[0]?.count??0;const pages=Math.max(1,Math.ceil(total/limit));const pageHref=(next:number)=>`/admin/orders?${new URLSearchParams({q,status,payment,page:String(next)})}`;
  return <AdminShell title="Orders" active="/admin/orders">
    <form method="get" className="mb-5 grid gap-3 border border-line bg-white p-4 sm:grid-cols-2 lg:grid-cols-[minmax(0,1fr)_180px_180px_auto_auto]"><label className="text-[11px] text-muted">Search<input name="q" defaultValue={q} placeholder="Order, email, phone or AWB" className="mt-1 h-10 w-full border border-line px-3 text-ink"/></label><label className="text-[11px] text-muted">Order state<select name="status" defaultValue={status} className="mt-1 h-10 w-full border border-line px-2"><option value="all">All orders</option>{["pending","confirmed","in_production","shipped","delivered","cancelled","refunded"].map(value=><option key={value}>{value}</option>)}<option value="shipment_error">Shipment failures</option></select></label><label className="text-[11px] text-muted">Payment<select name="payment" defaultValue={payment} className="mt-1 h-10 w-full border border-line px-2"><option value="all">All payments</option>{["pending","paid","failed","refunded","partially_refunded"].map(value=><option key={value}>{value}</option>)}</select></label><button className="h-10 self-end bg-ink px-5 text-white">Filter</button><Link href="/admin/orders" className="flex h-10 items-center self-end justify-center border border-line px-5">Reset</Link></form>
    <p className="mb-4 text-[13px] text-muted">{total} matching orders · page {Math.min(page,pages)} of {pages}. Status changes do not move money; refunds require payment reconciliation.</p>
    <div className="space-y-4">{rows.length===0&&<p className="border border-line bg-white p-8 text-muted">No orders match these filters.</p>}{rows.map(o=>{const closed=["cancelled","refunded"].includes(o.status);return <section key={o.id} className="border border-line bg-white p-5">{closed?<div className="flex flex-wrap items-start justify-between gap-4"><div><Link href={`/admin/orders/${o.id}`} className="font-medium underline">{o.number}</Link><p className="mt-1 text-[12px] text-muted">{shortDate(o.created_at)} · {o.email} · {o.items} items · {money(o.grand_total)}</p></div><span className="border border-line px-3 py-1 text-[12px]">{o.status} · {o.payment_status}</span></div>:<AdminForm action={updateOrder} className="grid gap-4 lg:grid-cols-[1fr_150px_160px_180px_auto] lg:items-end"><input type="hidden" name="id" value={o.id}/><div><div className="flex flex-wrap gap-3"><Link href={`/admin/orders/${o.id}`} className="font-medium underline">{o.number}</Link><span className={o.payment_status==='paid'?"text-[#5f7f06]":"text-muted"}>{o.payment_status}</span>{o.shipment_status&&<span className="text-muted">· {o.shipment_status}</span>}</div><p className="mt-1 text-[12px] text-muted">{shortDate(o.created_at)} · {o.email} · {o.items} items · {money(o.grand_total)}</p>{o.tracking_number&&<p className="mt-1 text-[12px] text-muted">{o.courier_name??'Courier'} · AWB {o.tracking_number}</p>}{o.shipment_error&&<p className="mt-2 text-[12px] text-[#a32d2d]">{o.shipment_error}</p>}</div><label className="text-[11px] text-muted">Order<select name="status" defaultValue={o.status} className="mt-1 h-10 w-full border border-line px-2 text-ink">{['pending','confirmed','in_production','shipped','delivered'].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-[11px] text-muted">Fulfilment<select name="fulfillment" defaultValue={o.fulfillment_status} className="mt-1 h-10 w-full border border-line px-2 text-ink">{['unfulfilled','processing','fulfilled','returned'].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-[11px] text-muted">Tracking<input name="tracking" defaultValue={o.tracking_number??''} className="mt-1 h-10 w-full border border-line px-3 text-ink"/></label><button className="h-10 bg-ink px-5 text-white">Save</button></AdminForm>}<div className="mt-4 flex flex-wrap items-center gap-3 border-t border-line pt-4">{o.payment_status==='paid'&&!closed&&<AdminForm action={bookShipment}><input type="hidden" name="id" value={o.id}/><button className="h-10 bg-lime px-5 text-ink">{o.shipment_id?'Complete / retry booking':'Book Shiprocket shipment'}</button></AdminForm>}{o.shipping_label_url&&<a href={o.shipping_label_url} target="_blank" rel="noreferrer" className="flex h-10 items-center border border-ink px-5 text-[12px]">Download label</a>}<Link href={`/admin/orders/${o.id}`} className="flex h-10 items-center border border-line px-5 text-[12px]">Open full order</Link></div></section>})}</div>
    {pages>1&&<nav className="mt-5 flex items-center justify-between"><span>{page>1?<Link className="border border-line bg-white px-5 py-2" href={pageHref(page-1)}>Previous</Link>:<span/>}</span><span className="text-[12px] text-muted">{page} / {pages}</span>{page<pages?<Link className="border border-line bg-white px-5 py-2" href={pageHref(page+1)}>Next</Link>:<span/>}</nav>}
  </AdminShell>;
}
